### ISSUE TITLE
[Installation Bug] Missing dns-sd.h

### ISSUE THREAD

**Issue by louisgv** [status-im/status-dev-cli#12]
![image](https://user-images.githubusercontent.com/6723574/26997949-e97fdd3c-4d32-11e7-9667-b917ae6d2f91.png)

According to mdns README:

```
https://www.npmjs.com/package/mdns
> On Linux and other systems using the avahi daemon the avahi dns_sd compat library and its header files are required. On debianesque systems the package name is libavahi-compat-libdnssd-dev. On other platforms Apple's mDNSResponder is recommended. Care should be taken not to install more than one mDNS stack on a system.

```

Thus installing `libavahi-compat-libdnssd-dev` solved this problem. This should be noted in the README.

**Comment by 3esmit** [comment]
I had the same problem, but to solve I had to install that package and navigate to `/usr/local/lib/node_modules/status-dev-cli` and `npm install mdns`

**Comment by jeluard** [comment]
Right depending on your OS `mdns` might have some pre-requisites.
We will update the doc to reflect this.
